version: "3"
services:
  api-database:
    image: mongo
    container_name: "ubsDB"
    ports:
    - 27017:27017
#  api:
#    image: fabiobatista04/api-java:0.1.0
#    container_name: "api"
#    ports:
#    - 8080:8080
#    links:
#    - api-database
