server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: remote

---

spring:
  data:
    mongodb:
      database: bionexo
      uri: mongodb+srv://fabio:admin@ubs.dtmaz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true
  config:
    activate:
      on-profile: remote
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---

spring:
  data:
    mongodb:
      database: bionexo
      host: localhost
      port: 27017
      auto-index-creation: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    activate:
      on-profile: local